# Generated by Django 4.2 on 2025-10-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
